FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /user/src/app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/http-server ./apps/http-server

RUN pnpm install --frozen-lockfile
RUN pnpm --filter db exec prisma generate
RUN pnpm --filter http-server run build

EXPOSE 3001

CMD ["sh", "-c", "pnpm --filter db exec prisma migrate deploy && pnpm --filter http-server run start"]
