FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /user/src/app


COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/web ./apps/web

RUN pnpm install --frozen-lockfile
RUN pnpm --filter db exec prisma generate
RUN pnpm --filter web run build

EXPOSE 3000

CMD ["pnpm", "--filter", "web", "run", "start"]
